apiVersion: v1
kind: Service
metadata:
  name: calculator-backend
spec:
  type: ClusterIP
  selector:
    app: calculator-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
