backend:
  replicas: 1
  image:
    tag: staging
    pullPolicy: IfNotPresent

frontend:
  replicas: 1
  image:
    tag: staging
    pullPolicy: IfNotPresent

ingress:
  host: staging.calculator.local
