CREATE DATABASE IF NOT EXISTS calculator;
USE calculator;

CREATE TABLE IF NOT EXISTS calc_history (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  expression VARCHAR(255) NOT NULL,
  result VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
