CREATE DATABASE IF NOT EXISTS calculator;
USE calculator;

CREATE DATABASE IF NOT EXISTS calculator;
USE calculator;

CREATE TABLE IF NOT EXISTS calc_history (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  a DOUBLE NOT NULL,
  b DOUBLE NOT NULL,
  op VARCHAR(10) NOT NULL,
  result DOUBLE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);